### ISSUE TITLE
Different sigma2 estimates than other methods 

### ISSUE THREAD

**Issue by jjustison** [larabreithaupt/seastaR#6]
Cool package with some neat utility that I've been playing around with. One thing I ran into is that when I use `sigma2_est` I get a different estimate of $\sigma^2$ than other approaches will give (e.g., `sigma2_phylo` from PhyloNetworks in Julia). 

I also tried implementing the equation for the MLE of rate  (a la [Adams 2013](https://doi.org/10.1093/sysbio/sys083)) in R and was getting different results. Looking at your code it seems that you used a similar approach but I wonder if there's an erroneous extra term

from your package the code is:

function (var_covar, trait) 
{
    num_taxa <- length(var_covar[, 1])
    if (num_taxa == length(trait)) {
        one <- c(rep(1, num_taxa))
        zhat_root <- (t(one) %*% solve(var_covar) %*% one) %*% 
            (t(one) %*% solve(var_covar) %*% trait)
        sigma2 <- ((t(trait - zhat_root * one)) %*% solve(var_covar) %*% 
            (trait - zhat_root * **one**))/(num_taxa - 1)
        return(sigma2)
    }
    else {
        stop("ERROR, trait vector is not the length of the number of taxa")
    }
}

When comparing to equation 1 of Adams 2013, he didn't have the bolded **one** in the computation and I think this might be part of what makes things different

**Comment by mhibbins** [comment]
Hi Joshua,

Thanks for your message and your interest in the software, and for pointing out this discrepancy with other estimators. I wrote a small script to test the effect of the bolded one term on estimates of simulated data (this term is included based on equation 4.8 in Luke Harmon's Phylogenetic Comparative Methods textbook). Here are the results: 

```
remove(list=ls())

library(seastaR)
library(ape)
library(geiger)
library(phytools)

sptree_example <- seastaR::parse_input_file(
  "C:/Users/mhibb/OneDrive - University of Toronto/Projects/seastaR_maintenance/seastaR_sptree_example.txt", genetrees = FALSE)

C_matrix <- ape::vcv(sptree_example)

test_traits <- seastaR::simulate_traits(1000, C_matrix, 1)

seastar_sig2_estimates <- apply(test_traits, 1, seastaR::sigma2_inference, 
                                var_covar = C_matrix)

print(mean(seastar_sig2_estimates))
```
1.060516

```
sigma2_inference_noone <- function(var_covar, trait){
  
  num_taxa <- length(var_covar[, 1])
  if (num_taxa == length(trait)){
    
    one <- c(rep(1, num_taxa))
    
    zhat_root <- (t(one)%*%solve(var_covar)%*%one)%*%(t(one)%*%solve(var_covar)%*%trait)
    sigma2 <- ((t(trait - zhat_root))%*%solve(var_covar)%*%(trait - zhat_root))/(num_taxa-1)
    
    return(sigma2)
  }
  else{
    stop("ERROR, trait vector is not the length of the number of taxa")
  }
  
}

noone_sig2_estimates <- apply(test_traits, 1, sigma2_inference_noone, 
                                var_covar = C_matrix)

print(mean(noone_sig2_estimates))
```
1.060516

So this doesn't seem to have any bearing on the result. To help you out I'll need a little more context - are you running this on simulated or empirical data? How different are the estimates? Are you using the species tree or gene tree covariance matrix? How many taxa? Also, a method that uses a ML search rather than the analytical estimator might return a different answer, depending on the shape of the likelihood surface (see our paper for more details). In this case I might be more inclined to trust the ML optimization approach, since the analytical solution can return very high estimates from the maximum of a nearly flat likelihood surface. Happy to help further,

Mark

**Comment by jjustison** [comment]
Ah sorry I don't think the **ones** was the issue, I just poorly read matrix math and notation. 

But upon further inspection I might guess that the issue is actually with how $\hat{z}(0)$ is computed. From eq 4.7 of Luke Harmon's book:
$$\hat{z}(0) = {(1^{T}C^{-1}1)}^{-1}{(1^{T}C^{-1}x)}$$

I don't think the function as written actually takes the inverse of that first term ${(1^{T}C^{-1}1)}$, which I think is causing the discrepancy I was having. As written in the function $\hat{z}(0)$ is:
```
zhat_root<- (t(one)%*%solve(var_covar)%*%one)%*%(t(one)%*%solve(var_covar)%*%trait)
```

If that's the issue then it should be fixed by wrapping it in `solve()`:
```
zhat_root<- solve(t(one)%*%solve(var_covar)%*%one)%*%(t(one)%*%solve(var_covar)%*%trait)
```

Apologies for the confusion on my end causing you to chase down a red herring with the simulations you ran in the last response

**Comment by mhibbins** [comment]
Hi Joshua,

Thanks for following up and no worries about the initial issue. You are correct that that inverse was missing, and I am getting slightly more accurate estimates from simulated data now with the fix in place. I will push an update that should correct the issue, so I am closing it for now, but let me know if you run into any more trouble. Thanks a bunch for finding this oversight. 

Mark
